####################################### Services
services:
  service-db-init-postgresql:
    build: .
    image: ahmetogguz/db-init-postgresql
    container_name: container-db-init-postgresql
    env_file:
      - ./.env
    restart: ${RESTART_POLICY}
    networks:
      - network-database

####################################### Networks
networks:
  network-database:
    external: true
